// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bpp.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessageLog = `-- name: InsertMessageLog :exec
INSERT INTO beckn_message_log (
    transaction_id, message_id,
    action, direction,
    url,
    bap_id, bap_uri,
    bpp_id, bpp_uri, network_id,
    ack_status,
    request_payload, response_payload,
    error_code, error_message,
    processing_duration_ms
) VALUES (
    $1, $2,
    $3, $4,
    $5,
    $6, $7,
    $8, $9, $10,
    $11,
    $12, $13,
    $14, $15,
    $16
)
`

type InsertMessageLogParams struct {
	TransactionID        pgtype.UUID      `json:"transaction_id"`
	MessageID            uuid.UUID        `json:"message_id"`
	Action               BecknAction      `json:"action"`
	Direction            MessageDirection `json:"direction"`
	Url                  *string          `json:"url"`
	BapID                *string          `json:"bap_id"`
	BapUri               *string          `json:"bap_uri"`
	BppID                *string          `json:"bpp_id"`
	BppUri               *string          `json:"bpp_uri"`
	NetworkID            *string          `json:"network_id"`
	AckStatus            NullAckStatus    `json:"ack_status"`
	RequestPayload       json.RawMessage  `json:"request_payload"`
	ResponsePayload      json.RawMessage  `json:"response_payload"`
	ErrorCode            *string          `json:"error_code"`
	ErrorMessage         *string          `json:"error_message"`
	ProcessingDurationMs *int32           `json:"processing_duration_ms"`
}

// Appends one immutable row to the beckn_message_log audit table.
// Called only for Beckn protocol API calls:
//
//	INBOUND  — a Beckn participant called one of our hosted endpoints
//	OUTBOUND — we called an external Beckn endpoint (CDS, BAP callback, etc.)
//
// Internal-only operations (DB queries, cache, etc.) are NOT logged here.
// Failures are warnings and must never abort the main request flow.
func (q *Queries) InsertMessageLog(ctx context.Context, arg InsertMessageLogParams) error {
	_, err := q.db.Exec(ctx, insertMessageLog,
		arg.TransactionID,
		arg.MessageID,
		arg.Action,
		arg.Direction,
		arg.Url,
		arg.BapID,
		arg.BapUri,
		arg.BppID,
		arg.BppUri,
		arg.NetworkID,
		arg.AckStatus,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ProcessingDurationMs,
	)
	return err
}

const upsertBPPIdentity = `-- name: UpsertBPPIdentity :exec

INSERT INTO bpp_identities (bpp_id, bpp_uri, network_ids, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (bpp_id) DO UPDATE SET
    bpp_uri     = EXCLUDED.bpp_uri,
    network_ids = EXCLUDED.network_ids,
    updated_at  = NOW()
`

type UpsertBPPIdentityParams struct {
	BppID      string   `json:"bpp_id"`
	BppUri     string   `json:"bpp_uri"`
	NetworkIds []string `json:"network_ids"`
}

// BPP infrastructure queries: identity seeding and message audit logging.
// Ensures this BPP's subscriber record exists before any tenant data is written.
// Called once at application startup using values from config / environment variables.
func (q *Queries) UpsertBPPIdentity(ctx context.Context, arg UpsertBPPIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertBPPIdentity, arg.BppID, arg.BppUri, arg.NetworkIds)
	return err
}
