// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: catalog.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCatalogOfferConsiderations = `-- name: DeleteCatalogOfferConsiderations :exec

DELETE FROM offer_considerations
WHERE catalog_id = $1 AND bpp_id = $2
`

type DeleteCatalogOfferConsiderationsParams struct {
	CatalogID string `json:"catalog_id"`
	BppID     string `json:"bpp_id"`
}

// ============================================================
// OFFERS
// ============================================================
func (q *Queries) DeleteCatalogOfferConsiderations(ctx context.Context, arg DeleteCatalogOfferConsiderationsParams) error {
	_, err := q.db.Exec(ctx, deleteCatalogOfferConsiderations, arg.CatalogID, arg.BppID)
	return err
}

const deleteCatalogOffers = `-- name: DeleteCatalogOffers :exec
DELETE FROM offers
WHERE catalog_id = $1 AND bpp_id = $2
`

type DeleteCatalogOffersParams struct {
	CatalogID string `json:"catalog_id"`
	BppID     string `json:"bpp_id"`
}

func (q *Queries) DeleteCatalogOffers(ctx context.Context, arg DeleteCatalogOffersParams) error {
	_, err := q.db.Exec(ctx, deleteCatalogOffers, arg.CatalogID, arg.BppID)
	return err
}

const deleteCatalogResources = `-- name: DeleteCatalogResources :exec

DELETE FROM resources
WHERE catalog_id = $1 AND bpp_id = $2
`

type DeleteCatalogResourcesParams struct {
	CatalogID string `json:"catalog_id"`
	BppID     string `json:"bpp_id"`
}

// ============================================================
// RESOURCES
// ============================================================
func (q *Queries) DeleteCatalogResources(ctx context.Context, arg DeleteCatalogResourcesParams) error {
	_, err := q.db.Exec(ctx, deleteCatalogResources, arg.CatalogID, arg.BppID)
	return err
}

const deleteProviderLocations = `-- name: DeleteProviderLocations :exec
DELETE FROM provider_locations
WHERE provider_id = $1 AND bpp_id = $2
`

type DeleteProviderLocationsParams struct {
	ProviderID string `json:"provider_id"`
	BppID      string `json:"bpp_id"`
}

func (q *Queries) DeleteProviderLocations(ctx context.Context, arg DeleteProviderLocationsParams) error {
	_, err := q.db.Exec(ctx, deleteProviderLocations, arg.ProviderID, arg.BppID)
	return err
}

const insertOffer = `-- name: InsertOffer :exec
INSERT INTO offers (
    id, catalog_id, bpp_id,
    provider_id,
    descriptor_name, descriptor_code, descriptor_short_desc,
    descriptor_docs, descriptor_media_files,
    resource_ids,
    offer_attributes, offer_attributes_context, offer_attributes_type,
    validity_start, validity_end
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6, $7,
    '[]', '[]',
    $8,
    $9, $10, $11,
    $12, $13
)
`

type InsertOfferParams struct {
	ID                     string             `json:"id"`
	CatalogID              string             `json:"catalog_id"`
	BppID                  string             `json:"bpp_id"`
	ProviderID             *string            `json:"provider_id"`
	DescriptorName         *string            `json:"descriptor_name"`
	DescriptorCode         *string            `json:"descriptor_code"`
	DescriptorShortDesc    *string            `json:"descriptor_short_desc"`
	ResourceIds            []string           `json:"resource_ids"`
	OfferAttributes        json.RawMessage    `json:"offer_attributes"`
	OfferAttributesContext *string            `json:"offer_attributes_context"`
	OfferAttributesType    *string            `json:"offer_attributes_type"`
	ValidityStart          pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd            pgtype.Timestamptz `json:"validity_end"`
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) error {
	_, err := q.db.Exec(ctx, insertOffer,
		arg.ID,
		arg.CatalogID,
		arg.BppID,
		arg.ProviderID,
		arg.DescriptorName,
		arg.DescriptorCode,
		arg.DescriptorShortDesc,
		arg.ResourceIds,
		arg.OfferAttributes,
		arg.OfferAttributesContext,
		arg.OfferAttributesType,
		arg.ValidityStart,
		arg.ValidityEnd,
	)
	return err
}

const insertOfferConsideration = `-- name: InsertOfferConsideration :exec
INSERT INTO offer_considerations (
    offer_id, catalog_id, bpp_id,
    consideration_id,
    status_code, status_name,
    consideration_attributes,
    consideration_attributes_context,
    consideration_attributes_type
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6,
    $7,
    $8, $9
)
`

type InsertOfferConsiderationParams struct {
	OfferID                        string          `json:"offer_id"`
	CatalogID                      string          `json:"catalog_id"`
	BppID                          string          `json:"bpp_id"`
	ConsiderationID                string          `json:"consideration_id"`
	StatusCode                     string          `json:"status_code"`
	StatusName                     *string         `json:"status_name"`
	ConsiderationAttributes        json.RawMessage `json:"consideration_attributes"`
	ConsiderationAttributesContext *string         `json:"consideration_attributes_context"`
	ConsiderationAttributesType    *string         `json:"consideration_attributes_type"`
}

func (q *Queries) InsertOfferConsideration(ctx context.Context, arg InsertOfferConsiderationParams) error {
	_, err := q.db.Exec(ctx, insertOfferConsideration,
		arg.OfferID,
		arg.CatalogID,
		arg.BppID,
		arg.ConsiderationID,
		arg.StatusCode,
		arg.StatusName,
		arg.ConsiderationAttributes,
		arg.ConsiderationAttributesContext,
		arg.ConsiderationAttributesType,
	)
	return err
}

const insertProviderLocation = `-- name: InsertProviderLocation :exec
INSERT INTO provider_locations (
    provider_id, bpp_id, geo,
    address_street, address_locality, address_region,
    address_country, address_postal_code, address_extended
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
`

type InsertProviderLocationParams struct {
	ProviderID        string          `json:"provider_id"`
	BppID             string          `json:"bpp_id"`
	Geo               json.RawMessage `json:"geo"`
	AddressStreet     *string         `json:"address_street"`
	AddressLocality   *string         `json:"address_locality"`
	AddressRegion     *string         `json:"address_region"`
	AddressCountry    *string         `json:"address_country"`
	AddressPostalCode *string         `json:"address_postal_code"`
	AddressExtended   *string         `json:"address_extended"`
}

func (q *Queries) InsertProviderLocation(ctx context.Context, arg InsertProviderLocationParams) error {
	_, err := q.db.Exec(ctx, insertProviderLocation,
		arg.ProviderID,
		arg.BppID,
		arg.Geo,
		arg.AddressStreet,
		arg.AddressLocality,
		arg.AddressRegion,
		arg.AddressCountry,
		arg.AddressPostalCode,
		arg.AddressExtended,
	)
	return err
}

const insertResource = `-- name: InsertResource :exec
INSERT INTO resources (
    id, catalog_id, bpp_id,
    descriptor_name, descriptor_code, descriptor_short_desc, descriptor_long_desc,
    descriptor_docs, descriptor_media_files,
    resource_attributes, resource_attributes_context, resource_attributes_type
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9,
    $10, $11, $12
)
`

type InsertResourceParams struct {
	ID                        string          `json:"id"`
	CatalogID                 string          `json:"catalog_id"`
	BppID                     string          `json:"bpp_id"`
	DescriptorName            *string         `json:"descriptor_name"`
	DescriptorCode            *string         `json:"descriptor_code"`
	DescriptorShortDesc       *string         `json:"descriptor_short_desc"`
	DescriptorLongDesc        *string         `json:"descriptor_long_desc"`
	DescriptorDocs            json.RawMessage `json:"descriptor_docs"`
	DescriptorMediaFiles      json.RawMessage `json:"descriptor_media_files"`
	ResourceAttributes        json.RawMessage `json:"resource_attributes"`
	ResourceAttributesContext *string         `json:"resource_attributes_context"`
	ResourceAttributesType    *string         `json:"resource_attributes_type"`
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.Exec(ctx, insertResource,
		arg.ID,
		arg.CatalogID,
		arg.BppID,
		arg.DescriptorName,
		arg.DescriptorCode,
		arg.DescriptorShortDesc,
		arg.DescriptorLongDesc,
		arg.DescriptorDocs,
		arg.DescriptorMediaFiles,
		arg.ResourceAttributes,
		arg.ResourceAttributesContext,
		arg.ResourceAttributesType,
	)
	return err
}

const upsertCatalog = `-- name: UpsertCatalog :exec

INSERT INTO catalogs (
    id, bpp_id, bpp_uri, provider_id,
    descriptor_name, descriptor_code, descriptor_short_desc, descriptor_long_desc,
    descriptor_docs, descriptor_media_files,
    is_active, catalog_type, update_mode,
    validity_start, validity_end,
    version, schema_context
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    true, $11, 'FULL',
    $12, $13,
    1, '[]'
)
ON CONFLICT (id, bpp_id) DO UPDATE SET
    bpp_uri              = EXCLUDED.bpp_uri,
    provider_id          = EXCLUDED.provider_id,
    descriptor_name      = EXCLUDED.descriptor_name,
    descriptor_code      = EXCLUDED.descriptor_code,
    descriptor_short_desc = EXCLUDED.descriptor_short_desc,
    descriptor_long_desc = EXCLUDED.descriptor_long_desc,
    descriptor_docs      = EXCLUDED.descriptor_docs,
    descriptor_media_files = EXCLUDED.descriptor_media_files,
    catalog_type         = EXCLUDED.catalog_type,
    validity_start       = EXCLUDED.validity_start,
    validity_end         = EXCLUDED.validity_end,
    version              = catalogs.version + 1,
    updated_at           = NOW()
`

type UpsertCatalogParams struct {
	ID                   string             `json:"id"`
	BppID                string             `json:"bpp_id"`
	BppUri               string             `json:"bpp_uri"`
	ProviderID           string             `json:"provider_id"`
	DescriptorName       string             `json:"descriptor_name"`
	DescriptorCode       *string            `json:"descriptor_code"`
	DescriptorShortDesc  *string            `json:"descriptor_short_desc"`
	DescriptorLongDesc   *string            `json:"descriptor_long_desc"`
	DescriptorDocs       json.RawMessage    `json:"descriptor_docs"`
	DescriptorMediaFiles json.RawMessage    `json:"descriptor_media_files"`
	CatalogType          NullCatalogType    `json:"catalog_type"`
	ValidityStart        pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd          pgtype.Timestamptz `json:"validity_end"`
}

// ============================================================
// CATALOGS
// ============================================================
func (q *Queries) UpsertCatalog(ctx context.Context, arg UpsertCatalogParams) error {
	_, err := q.db.Exec(ctx, upsertCatalog,
		arg.ID,
		arg.BppID,
		arg.BppUri,
		arg.ProviderID,
		arg.DescriptorName,
		arg.DescriptorCode,
		arg.DescriptorShortDesc,
		arg.DescriptorLongDesc,
		arg.DescriptorDocs,
		arg.DescriptorMediaFiles,
		arg.CatalogType,
		arg.ValidityStart,
		arg.ValidityEnd,
	)
	return err
}

const upsertProvider = `-- name: UpsertProvider :exec


INSERT INTO providers (
    id, bpp_id,
    descriptor_name, descriptor_code, descriptor_short_desc, descriptor_long_desc,
    descriptor_docs, descriptor_media_files,
    is_active
) VALUES (
    $1, $2,
    $3, $4, $5, $6,
    $7, $8,
    true
)
ON CONFLICT (id, bpp_id) DO UPDATE SET
    descriptor_name      = EXCLUDED.descriptor_name,
    descriptor_code      = EXCLUDED.descriptor_code,
    descriptor_short_desc = EXCLUDED.descriptor_short_desc,
    descriptor_long_desc = EXCLUDED.descriptor_long_desc,
    descriptor_docs      = EXCLUDED.descriptor_docs,
    descriptor_media_files = EXCLUDED.descriptor_media_files,
    updated_at           = NOW()
`

type UpsertProviderParams struct {
	ID                   string          `json:"id"`
	BppID                string          `json:"bpp_id"`
	DescriptorName       string          `json:"descriptor_name"`
	DescriptorCode       *string         `json:"descriptor_code"`
	DescriptorShortDesc  *string         `json:"descriptor_short_desc"`
	DescriptorLongDesc   *string         `json:"descriptor_long_desc"`
	DescriptorDocs       json.RawMessage `json:"descriptor_docs"`
	DescriptorMediaFiles json.RawMessage `json:"descriptor_media_files"`
}

// Catalog publishing queries.
// All operations use upsert or delete+insert to support FULL update mode.
// ============================================================
// PROVIDERS
// ============================================================
func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) error {
	_, err := q.db.Exec(ctx, upsertProvider,
		arg.ID,
		arg.BppID,
		arg.DescriptorName,
		arg.DescriptorCode,
		arg.DescriptorShortDesc,
		arg.DescriptorLongDesc,
		arg.DescriptorDocs,
		arg.DescriptorMediaFiles,
	)
	return err
}
