// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: confirm.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const confirmContract = `-- name: ConfirmContract :one

UPDATE contracts SET
    status     = 'ACTIVE'::contract_status,
    updated_at = NOW()
WHERE transaction_id = $1
  AND bpp_id = $2
  AND status = 'DRAFT'::contract_status
  AND deleted_at IS NULL
RETURNING id
`

type ConfirmContractParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	BppID         string    `json:"bpp_id"`
}

// Queries for the /beckn/confirm handler.
// Confirm transitions the contract from DRAFT → ACTIVE.
// The contract MUST already exist (created during init).
// Transitions a DRAFT contract to ACTIVE status.
// Returns the contract id on success; errors if no DRAFT contract is found.
func (q *Queries) ConfirmContract(ctx context.Context, arg ConfirmContractParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, confirmContract, arg.TransactionID, arg.BppID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
