// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContracts = `-- name: CountContracts :one
SELECT COUNT(*) FROM contracts
WHERE bpp_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountContracts(ctx context.Context, bppID string) (int64, error) {
	row := q.db.QueryRow(ctx, countContracts, bppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOffers = `-- name: CountOffers :one
SELECT COUNT(*) FROM offers
WHERE bpp_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountOffers(ctx context.Context, bppID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOffers, bppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resources
WHERE bpp_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountResources(ctx context.Context, bppID string) (int64, error) {
	row := q.db.QueryRow(ctx, countResources, bppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContractDetail = `-- name: GetContractDetail :one
SELECT
    c.id,
    c.transaction_id,
    c.status,
    c.bap_id,
    c.bap_uri,
    c.domain,
    c.created_at,
    c.updated_at
FROM contracts c
WHERE c.id = $1
  AND c.bpp_id = $2
`

type GetContractDetailParams struct {
	ID    uuid.UUID `json:"id"`
	BppID string    `json:"bpp_id"`
}

type GetContractDetailRow struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	Status        ContractStatus     `json:"status"`
	BapID         string             `json:"bap_id"`
	BapUri        string             `json:"bap_uri"`
	Domain        *string            `json:"domain"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContractDetail(ctx context.Context, arg GetContractDetailParams) (GetContractDetailRow, error) {
	row := q.db.QueryRow(ctx, getContractDetail, arg.ID, arg.BppID)
	var i GetContractDetailRow
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Status,
		&i.BapID,
		&i.BapUri,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one


SELECT
    COUNT(*) FILTER (WHERE status = 'ACTIVE')                           AS active_orders,
    COUNT(*) FILTER (WHERE status = 'DRAFT')                            AS pending_orders,
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours')    AS today_orders
FROM contracts
WHERE bpp_id = $1
  AND deleted_at IS NULL
`

type GetDashboardStatsRow struct {
	ActiveOrders  int64 `json:"active_orders"`
	PendingOrders int64 `json:"pending_orders"`
	TodayOrders   int64 `json:"today_orders"`
}

// Dashboard queries for the BPP admin panel.
// ============================================================
// STATS
// ============================================================
func (q *Queries) GetDashboardStats(ctx context.Context, bppID string) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, bppID)
	var i GetDashboardStatsRow
	err := row.Scan(&i.ActiveOrders, &i.PendingOrders, &i.TodayOrders)
	return i, err
}

const getInventoryStats = `-- name: GetInventoryStats :one
SELECT
    (SELECT COUNT(*) FROM resources r2 WHERE r2.bpp_id = $1 AND r2.deleted_at IS NULL) AS resource_count,
    (SELECT COUNT(*) FROM offers    o2 WHERE o2.bpp_id = $1 AND o2.deleted_at IS NULL) AS offer_count
`

type GetInventoryStatsRow struct {
	ResourceCount int64 `json:"resource_count"`
	OfferCount    int64 `json:"offer_count"`
}

func (q *Queries) GetInventoryStats(ctx context.Context, bppID string) (GetInventoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getInventoryStats, bppID)
	var i GetInventoryStatsRow
	err := row.Scan(&i.ResourceCount, &i.OfferCount)
	return i, err
}

const getMessageFunnel = `-- name: GetMessageFunnel :many
SELECT
    action,
    COUNT(*) AS message_count
FROM beckn_message_log
WHERE bpp_id = $1
  AND action IN ('select', 'init', 'confirm')
  AND direction = 'INBOUND'
GROUP BY action
ORDER BY action
`

type GetMessageFunnelRow struct {
	Action       BecknAction `json:"action"`
	MessageCount int64       `json:"message_count"`
}

func (q *Queries) GetMessageFunnel(ctx context.Context, bppID *string) ([]GetMessageFunnelRow, error) {
	rows, err := q.db.Query(ctx, getMessageFunnel, bppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessageFunnelRow{}
	for rows.Next() {
		var i GetMessageFunnelRow
		if err := rows.Scan(&i.Action, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractCommitments = `-- name: ListContractCommitments :many
SELECT
    cm.id,
    cm.status,
    cm.commitment_attributes,
    co.offer_id,
    co.offer_descriptor,
    co.resource_ids
FROM commitments cm
LEFT JOIN commitment_offers co ON co.commitment_id = cm.id AND co.contract_id = cm.contract_id
WHERE cm.contract_id = $1
ORDER BY cm.created_at
`

type ListContractCommitmentsRow struct {
	ID                   string           `json:"id"`
	Status               CommitmentStatus `json:"status"`
	CommitmentAttributes json.RawMessage  `json:"commitment_attributes"`
	OfferID              *string          `json:"offer_id"`
	OfferDescriptor      json.RawMessage  `json:"offer_descriptor"`
	ResourceIds          []string         `json:"resource_ids"`
}

func (q *Queries) ListContractCommitments(ctx context.Context, contractID uuid.UUID) ([]ListContractCommitmentsRow, error) {
	rows, err := q.db.Query(ctx, listContractCommitments, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractCommitmentsRow{}
	for rows.Next() {
		var i ListContractCommitmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CommitmentAttributes,
			&i.OfferID,
			&i.OfferDescriptor,
			&i.ResourceIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractConsiderations = `-- name: ListContractConsiderations :many
SELECT
    id,
    status_code,
    status_name,
    consideration_attributes
FROM considerations
WHERE contract_id = $1
`

type ListContractConsiderationsRow struct {
	ID                      string          `json:"id"`
	StatusCode              string          `json:"status_code"`
	StatusName              *string         `json:"status_name"`
	ConsiderationAttributes json.RawMessage `json:"consideration_attributes"`
}

func (q *Queries) ListContractConsiderations(ctx context.Context, contractID uuid.UUID) ([]ListContractConsiderationsRow, error) {
	rows, err := q.db.Query(ctx, listContractConsiderations, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractConsiderationsRow{}
	for rows.Next() {
		var i ListContractConsiderationsRow
		if err := rows.Scan(
			&i.ID,
			&i.StatusCode,
			&i.StatusName,
			&i.ConsiderationAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContracts = `-- name: ListContracts :many

SELECT
    c.id,
    c.transaction_id,
    c.status,
    c.bap_id,
    c.created_at,
    COALESCE(co.offer_descriptor, '{}') AS offer_descriptor
FROM contracts c
LEFT JOIN LATERAL (
    SELECT co2.offer_descriptor
    FROM commitment_offers co2
    JOIN commitments cm ON cm.id = co2.commitment_id AND cm.contract_id = co2.contract_id
    WHERE cm.contract_id = c.id
    LIMIT 1
) co ON TRUE
WHERE c.bpp_id = $1
  AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT  $2
OFFSET $3
`

type ListContractsParams struct {
	BppID  string `json:"bpp_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListContractsRow struct {
	ID              uuid.UUID          `json:"id"`
	TransactionID   uuid.UUID          `json:"transaction_id"`
	Status          ContractStatus     `json:"status"`
	BapID           string             `json:"bap_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	OfferDescriptor json.RawMessage    `json:"offer_descriptor"`
}

// ============================================================
// CONTRACTS / ORDERS
// ============================================================
func (q *Queries) ListContracts(ctx context.Context, arg ListContractsParams) ([]ListContractsRow, error) {
	rows, err := q.db.Query(ctx, listContracts, arg.BppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractsRow{}
	for rows.Next() {
		var i ListContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Status,
			&i.BapID,
			&i.CreatedAt,
			&i.OfferDescriptor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferConsiderations = `-- name: ListOfferConsiderations :many
SELECT
    consideration_id,
    status_code,
    status_name,
    consideration_attributes
FROM offer_considerations
WHERE offer_id = $1
  AND bpp_id   = $2
`

type ListOfferConsiderationsParams struct {
	OfferID string `json:"offer_id"`
	BppID   string `json:"bpp_id"`
}

type ListOfferConsiderationsRow struct {
	ConsiderationID         string          `json:"consideration_id"`
	StatusCode              string          `json:"status_code"`
	StatusName              *string         `json:"status_name"`
	ConsiderationAttributes json.RawMessage `json:"consideration_attributes"`
}

func (q *Queries) ListOfferConsiderations(ctx context.Context, arg ListOfferConsiderationsParams) ([]ListOfferConsiderationsRow, error) {
	rows, err := q.db.Query(ctx, listOfferConsiderations, arg.OfferID, arg.BppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOfferConsiderationsRow{}
	for rows.Next() {
		var i ListOfferConsiderationsRow
		if err := rows.Scan(
			&i.ConsiderationID,
			&i.StatusCode,
			&i.StatusName,
			&i.ConsiderationAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOffers = `-- name: ListOffers :many

SELECT
    o.id,
    o.catalog_id,
    o.descriptor_name,
    o.descriptor_short_desc,
    o.resource_ids,
    o.validity_start,
    o.validity_end,
    o.created_at
FROM offers o
WHERE o.bpp_id = $1
  AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
LIMIT  $2
OFFSET $3
`

type ListOffersParams struct {
	BppID  string `json:"bpp_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListOffersRow struct {
	ID                  string             `json:"id"`
	CatalogID           string             `json:"catalog_id"`
	DescriptorName      *string            `json:"descriptor_name"`
	DescriptorShortDesc *string            `json:"descriptor_short_desc"`
	ResourceIds         []string           `json:"resource_ids"`
	ValidityStart       pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd         pgtype.Timestamptz `json:"validity_end"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// OFFERS
// ============================================================
func (q *Queries) ListOffers(ctx context.Context, arg ListOffersParams) ([]ListOffersRow, error) {
	rows, err := q.db.Query(ctx, listOffers, arg.BppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffersRow{}
	for rows.Next() {
		var i ListOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.DescriptorName,
			&i.DescriptorShortDesc,
			&i.ResourceIds,
			&i.ValidityStart,
			&i.ValidityEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many

SELECT
    action,
    direction,
    ack_status,
    transaction_id,
    url,
    created_at
FROM beckn_message_log
WHERE bpp_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentMessagesParams struct {
	BppID *string `json:"bpp_id"`
	Limit int32   `json:"limit"`
}

type ListRecentMessagesRow struct {
	Action        BecknAction        `json:"action"`
	Direction     MessageDirection   `json:"direction"`
	AckStatus     NullAckStatus      `json:"ack_status"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	Url           *string            `json:"url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// MESSAGE LOG
// ============================================================
func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]ListRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, arg.BppID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentMessagesRow{}
	for rows.Next() {
		var i ListRecentMessagesRow
		if err := rows.Scan(
			&i.Action,
			&i.Direction,
			&i.AckStatus,
			&i.TransactionID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many

SELECT
    r.id,
    r.catalog_id,
    r.descriptor_name,
    r.descriptor_short_desc,
    r.resource_attributes,
    r.created_at
FROM resources r
WHERE r.bpp_id = $1
  AND r.deleted_at IS NULL
ORDER BY r.created_at DESC
LIMIT  $2
OFFSET $3
`

type ListResourcesParams struct {
	BppID  string `json:"bpp_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListResourcesRow struct {
	ID                  string             `json:"id"`
	CatalogID           string             `json:"catalog_id"`
	DescriptorName      *string            `json:"descriptor_name"`
	DescriptorShortDesc *string            `json:"descriptor_short_desc"`
	ResourceAttributes  json.RawMessage    `json:"resource_attributes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// RESOURCES
// ============================================================
func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources, arg.BppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.DescriptorName,
			&i.DescriptorShortDesc,
			&i.ResourceAttributes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
