// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fulfillment.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelContract = `-- name: CancelContract :one

UPDATE contracts SET
    status     = 'CANCELLED'::contract_status,
    updated_at = NOW()
WHERE transaction_id = $1
  AND bpp_id = $2
  AND status = 'ACTIVE'::contract_status
  AND deleted_at IS NULL
RETURNING id, bap_id, bap_uri
`

type CancelContractParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	BppID         string    `json:"bpp_id"`
}

type CancelContractRow struct {
	ID     uuid.UUID `json:"id"`
	BapID  string    `json:"bap_id"`
	BapUri string    `json:"bap_uri"`
}

// ============================================================
// CANCEL — transition ACTIVE → CANCELLED
// ============================================================
// Transitions an ACTIVE contract to CANCELLED.
// Returns bap_uri and bap_id so the service can call on_cancel.
func (q *Queries) CancelContract(ctx context.Context, arg CancelContractParams) (CancelContractRow, error) {
	row := q.db.QueryRow(ctx, cancelContract, arg.TransactionID, arg.BppID)
	var i CancelContractRow
	err := row.Scan(&i.ID, &i.BapID, &i.BapUri)
	return i, err
}

const countRatings = `-- name: CountRatings :one
SELECT COUNT(*) FROM ratings r
JOIN contracts c ON c.id = r.contract_id
WHERE c.bpp_id = $1
`

func (q *Queries) CountRatings(ctx context.Context, bppID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRatings, bppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSupportTickets = `-- name: CountSupportTickets :one
SELECT COUNT(*) FROM support_tickets st
LEFT JOIN contracts c ON c.id = st.contract_id
WHERE c.bpp_id = $1 OR st.contract_id IS NULL
`

func (q *Queries) CountSupportTickets(ctx context.Context, bppID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSupportTickets, bppID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveContractByTxnID = `-- name: GetActiveContractByTxnID :one


SELECT
    c.id,
    c.bap_id,
    c.bap_uri,
    c.status,
    c.transaction_id,
    c.network_id,
    c.domain,
    c.contract_attributes,
    c.created_at,
    c.updated_at
FROM contracts c
WHERE c.transaction_id = $1
  AND c.bpp_id = $2
  AND c.deleted_at IS NULL
LIMIT 1
`

type GetActiveContractByTxnIDParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	BppID         string    `json:"bpp_id"`
}

type GetActiveContractByTxnIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	BapID              string             `json:"bap_id"`
	BapUri             string             `json:"bap_uri"`
	Status             ContractStatus     `json:"status"`
	TransactionID      uuid.UUID          `json:"transaction_id"`
	NetworkID          *string            `json:"network_id"`
	Domain             *string            `json:"domain"`
	ContractAttributes json.RawMessage    `json:"contract_attributes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Queries for fulfillment actions: status, cancel, update, rate, support.
// ============================================================
// STATUS — look up full contract for on_status callback
// ============================================================
// Returns core contract fields needed to build an on_status payload.
func (q *Queries) GetActiveContractByTxnID(ctx context.Context, arg GetActiveContractByTxnIDParams) (GetActiveContractByTxnIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveContractByTxnID, arg.TransactionID, arg.BppID)
	var i GetActiveContractByTxnIDRow
	err := row.Scan(
		&i.ID,
		&i.BapID,
		&i.BapUri,
		&i.Status,
		&i.TransactionID,
		&i.NetworkID,
		&i.Domain,
		&i.ContractAttributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitmentResourceIDsByContractID = `-- name: GetCommitmentResourceIDsByContractID :many
SELECT DISTINCT cr.resource_id
FROM commitment_resources cr
JOIN commitments cm ON cm.id = cr.commitment_id AND cm.contract_id = cr.contract_id
WHERE cm.contract_id = $1
`

// Returns all committed resource IDs for a contract (used to restore stock on cancel).
func (q *Queries) GetCommitmentResourceIDsByContractID(ctx context.Context, contractID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getCommitmentResourceIDsByContractID, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource_id string
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRating = `-- name: InsertRating :exec

INSERT INTO ratings (
    contract_id,
    bap_id,
    bap_uri,
    target_id,
    target_descriptor,
    range,
    feedback_form_submission,
    is_preview
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRatingParams struct {
	ContractID             uuid.UUID       `json:"contract_id"`
	BapID                  string          `json:"bap_id"`
	BapUri                 string          `json:"bap_uri"`
	TargetID               string          `json:"target_id"`
	TargetDescriptor       json.RawMessage `json:"target_descriptor"`
	Range                  json.RawMessage `json:"range"`
	FeedbackFormSubmission json.RawMessage `json:"feedback_form_submission"`
	IsPreview              bool            `json:"is_preview"`
}

// ============================================================
// RATE — persist rating inputs
// ============================================================
func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) error {
	_, err := q.db.Exec(ctx, insertRating,
		arg.ContractID,
		arg.BapID,
		arg.BapUri,
		arg.TargetID,
		arg.TargetDescriptor,
		arg.Range,
		arg.FeedbackFormSubmission,
		arg.IsPreview,
	)
	return err
}

const insertSupportTicket = `-- name: InsertSupportTicket :one

INSERT INTO support_tickets (
    contract_id,
    bap_id,
    bap_uri,
    descriptor_name,
    descriptor_short_desc,
    channels,
    is_preview
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertSupportTicketParams struct {
	ContractID          pgtype.UUID     `json:"contract_id"`
	BapID               string          `json:"bap_id"`
	BapUri              string          `json:"bap_uri"`
	DescriptorName      *string         `json:"descriptor_name"`
	DescriptorShortDesc *string         `json:"descriptor_short_desc"`
	Channels            json.RawMessage `json:"channels"`
	IsPreview           bool            `json:"is_preview"`
}

// ============================================================
// SUPPORT — persist support tickets
// ============================================================
func (q *Queries) InsertSupportTicket(ctx context.Context, arg InsertSupportTicketParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSupportTicket,
		arg.ContractID,
		arg.BapID,
		arg.BapUri,
		arg.DescriptorName,
		arg.DescriptorShortDesc,
		arg.Channels,
		arg.IsPreview,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRatings = `-- name: ListRatings :many
SELECT
    r.id,
    r.contract_id,
    c.transaction_id,
    r.bap_id,
    r.target_id,
    r.target_descriptor,
    r.range,
    r.feedback_form_submission,
    r.is_preview,
    r.created_at
FROM ratings r
JOIN contracts c ON c.id = r.contract_id
WHERE c.bpp_id = $1
ORDER BY r.created_at DESC
LIMIT  $2
OFFSET $3
`

type ListRatingsParams struct {
	BppID  string `json:"bpp_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListRatingsRow struct {
	ID                     uuid.UUID          `json:"id"`
	ContractID             uuid.UUID          `json:"contract_id"`
	TransactionID          uuid.UUID          `json:"transaction_id"`
	BapID                  string             `json:"bap_id"`
	TargetID               string             `json:"target_id"`
	TargetDescriptor       json.RawMessage    `json:"target_descriptor"`
	Range                  json.RawMessage    `json:"range"`
	FeedbackFormSubmission json.RawMessage    `json:"feedback_form_submission"`
	IsPreview              bool               `json:"is_preview"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRatings(ctx context.Context, arg ListRatingsParams) ([]ListRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRatings, arg.BppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRatingsRow{}
	for rows.Next() {
		var i ListRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.TransactionID,
			&i.BapID,
			&i.TargetID,
			&i.TargetDescriptor,
			&i.Range,
			&i.FeedbackFormSubmission,
			&i.IsPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportTickets = `-- name: ListSupportTickets :many
SELECT
    st.id,
    st.contract_id,
    c.transaction_id,
    st.bap_id,
    st.descriptor_name,
    st.descriptor_short_desc,
    st.channels,
    st.status,
    st.is_preview,
    st.created_at,
    st.resolved_at
FROM support_tickets st
LEFT JOIN contracts c ON c.id = st.contract_id
WHERE (c.bpp_id = $1 OR st.contract_id IS NULL)
ORDER BY st.created_at DESC
LIMIT  $2
OFFSET $3
`

type ListSupportTicketsParams struct {
	BppID  string `json:"bpp_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListSupportTicketsRow struct {
	ID                  uuid.UUID           `json:"id"`
	ContractID          pgtype.UUID         `json:"contract_id"`
	TransactionID       pgtype.UUID         `json:"transaction_id"`
	BapID               string              `json:"bap_id"`
	DescriptorName      *string             `json:"descriptor_name"`
	DescriptorShortDesc *string             `json:"descriptor_short_desc"`
	Channels            json.RawMessage     `json:"channels"`
	Status              SupportTicketStatus `json:"status"`
	IsPreview           bool                `json:"is_preview"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	ResolvedAt          pgtype.Timestamptz  `json:"resolved_at"`
}

func (q *Queries) ListSupportTickets(ctx context.Context, arg ListSupportTicketsParams) ([]ListSupportTicketsRow, error) {
	rows, err := q.db.Query(ctx, listSupportTickets, arg.BppID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSupportTicketsRow{}
	for rows.Next() {
		var i ListSupportTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.TransactionID,
			&i.BapID,
			&i.DescriptorName,
			&i.DescriptorShortDesc,
			&i.Channels,
			&i.Status,
			&i.IsPreview,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
