// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: init.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getContractByTransactionID = `-- name: GetContractByTransactionID :one

SELECT id FROM contracts
WHERE transaction_id = $1
  AND bpp_id = $2
  AND status = 'DRAFT'::contract_status
  AND deleted_at IS NULL
LIMIT 1
`

type GetContractByTransactionIDParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	BppID         string    `json:"bpp_id"`
}

// Queries for the /beckn/init handler.
// These persist contract state derived from the BAP's init request.
// The transactionId (from Beckn context) is the stable key across the
// discover→select→init→confirm lifecycle.
// Look up the existing DRAFT contract for this session (if any).
func (q *Queries) GetContractByTransactionID(ctx context.Context, arg GetContractByTransactionIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getContractByTransactionID, arg.TransactionID, arg.BppID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertContract = `-- name: InsertContract :one
INSERT INTO contracts (
    id,
    bpp_id,
    bap_id,
    bap_uri,
    transaction_id,
    network_id,
    status,
    contract_attributes,
    contract_attributes_context,
    contract_attributes_type
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    'DRAFT'::contract_status,
    $7, $8, $9
)
RETURNING id
`

type InsertContractParams struct {
	ID                        uuid.UUID       `json:"id"`
	BppID                     string          `json:"bpp_id"`
	BapID                     string          `json:"bap_id"`
	BapUri                    string          `json:"bap_uri"`
	TransactionID             uuid.UUID       `json:"transaction_id"`
	NetworkID                 *string         `json:"network_id"`
	ContractAttributes        json.RawMessage `json:"contract_attributes"`
	ContractAttributesContext *string         `json:"contract_attributes_context"`
	ContractAttributesType    *string         `json:"contract_attributes_type"`
}

// Create a new contract row for this init request.
func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertContract,
		arg.ID,
		arg.BppID,
		arg.BapID,
		arg.BapUri,
		arg.TransactionID,
		arg.NetworkID,
		arg.ContractAttributes,
		arg.ContractAttributesContext,
		arg.ContractAttributesType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateContractAttributes = `-- name: UpdateContractAttributes :exec
UPDATE contracts SET
    bap_uri                     = $2,
    contract_attributes         = $3,
    contract_attributes_context = $4,
    contract_attributes_type    = $5,
    updated_at                  = NOW()
WHERE id = $1
`

type UpdateContractAttributesParams struct {
	ID                        uuid.UUID       `json:"id"`
	BapUri                    string          `json:"bap_uri"`
	ContractAttributes        json.RawMessage `json:"contract_attributes"`
	ContractAttributesContext *string         `json:"contract_attributes_context"`
	ContractAttributesType    *string         `json:"contract_attributes_type"`
}

// Refresh mutable fields on an existing contract (called when contract already exists).
func (q *Queries) UpdateContractAttributes(ctx context.Context, arg UpdateContractAttributesParams) error {
	_, err := q.db.Exec(ctx, updateContractAttributes,
		arg.ID,
		arg.BapUri,
		arg.ContractAttributes,
		arg.ContractAttributesContext,
		arg.ContractAttributesType,
	)
	return err
}

const upsertCommitment = `-- name: UpsertCommitment :exec
INSERT INTO commitments (
    id,
    contract_id,
    status,
    commitment_attributes,
    commitment_attributes_context,
    commitment_attributes_type
)
VALUES (
    $1, $2,
    'DRAFT'::commitment_status,
    $3, $4, $5
)
ON CONFLICT (id, contract_id)
    DO UPDATE SET
        commitment_attributes         = EXCLUDED.commitment_attributes,
        commitment_attributes_context = EXCLUDED.commitment_attributes_context,
        commitment_attributes_type    = EXCLUDED.commitment_attributes_type,
        updated_at                    = NOW()
`

type UpsertCommitmentParams struct {
	ID                          string          `json:"id"`
	ContractID                  uuid.UUID       `json:"contract_id"`
	CommitmentAttributes        json.RawMessage `json:"commitment_attributes"`
	CommitmentAttributesContext *string         `json:"commitment_attributes_context"`
	CommitmentAttributesType    *string         `json:"commitment_attributes_type"`
}

// Inserts or refreshes a commitment row linked to the contract.
func (q *Queries) UpsertCommitment(ctx context.Context, arg UpsertCommitmentParams) error {
	_, err := q.db.Exec(ctx, upsertCommitment,
		arg.ID,
		arg.ContractID,
		arg.CommitmentAttributes,
		arg.CommitmentAttributesContext,
		arg.CommitmentAttributesType,
	)
	return err
}

const upsertCommitmentOffer = `-- name: UpsertCommitmentOffer :exec
INSERT INTO commitment_offers (
    commitment_id,
    contract_id,
    offer_id,
    offer_descriptor,
    offer_attributes,
    resource_ids
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (commitment_id, contract_id)
    DO UPDATE SET
        offer_id         = EXCLUDED.offer_id,
        offer_descriptor = EXCLUDED.offer_descriptor,
        offer_attributes = EXCLUDED.offer_attributes,
        resource_ids     = EXCLUDED.resource_ids
`

type UpsertCommitmentOfferParams struct {
	CommitmentID    string          `json:"commitment_id"`
	ContractID      uuid.UUID       `json:"contract_id"`
	OfferID         string          `json:"offer_id"`
	OfferDescriptor json.RawMessage `json:"offer_descriptor"`
	OfferAttributes json.RawMessage `json:"offer_attributes"`
	ResourceIds     []string        `json:"resource_ids"`
}

// Inserts or refreshes the offer snapshot for a commitment.
func (q *Queries) UpsertCommitmentOffer(ctx context.Context, arg UpsertCommitmentOfferParams) error {
	_, err := q.db.Exec(ctx, upsertCommitmentOffer,
		arg.CommitmentID,
		arg.ContractID,
		arg.OfferID,
		arg.OfferDescriptor,
		arg.OfferAttributes,
		arg.ResourceIds,
	)
	return err
}

const upsertConsideration = `-- name: UpsertConsideration :exec
INSERT INTO considerations (
    id,
    contract_id,
    status_code,
    consideration_attributes,
    consideration_attributes_context,
    consideration_attributes_type
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id, contract_id)
    DO UPDATE SET
        status_code                      = EXCLUDED.status_code,
        consideration_attributes         = EXCLUDED.consideration_attributes,
        consideration_attributes_context = EXCLUDED.consideration_attributes_context,
        consideration_attributes_type    = EXCLUDED.consideration_attributes_type,
        updated_at                       = NOW()
`

type UpsertConsiderationParams struct {
	ID                             string          `json:"id"`
	ContractID                     uuid.UUID       `json:"contract_id"`
	StatusCode                     string          `json:"status_code"`
	ConsiderationAttributes        json.RawMessage `json:"consideration_attributes"`
	ConsiderationAttributesContext *string         `json:"consideration_attributes_context"`
	ConsiderationAttributesType    *string         `json:"consideration_attributes_type"`
}

// Inserts or refreshes a consideration (pricing) row for the contract.
func (q *Queries) UpsertConsideration(ctx context.Context, arg UpsertConsiderationParams) error {
	_, err := q.db.Exec(ctx, upsertConsideration,
		arg.ID,
		arg.ContractID,
		arg.StatusCode,
		arg.ConsiderationAttributes,
		arg.ConsiderationAttributesContext,
		arg.ConsiderationAttributesType,
	)
	return err
}

const upsertParticipant = `-- name: UpsertParticipant :exec
INSERT INTO contract_participants (
    id,
    contract_id,
    descriptor_name,
    participant_attributes,
    participant_attributes_context,
    participant_attributes_type
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id, contract_id)
    DO UPDATE SET
        descriptor_name                = EXCLUDED.descriptor_name,
        participant_attributes         = EXCLUDED.participant_attributes,
        participant_attributes_context = EXCLUDED.participant_attributes_context,
        participant_attributes_type    = EXCLUDED.participant_attributes_type,
        updated_at                     = NOW()
`

type UpsertParticipantParams struct {
	ID                           string          `json:"id"`
	ContractID                   uuid.UUID       `json:"contract_id"`
	DescriptorName               *string         `json:"descriptor_name"`
	ParticipantAttributes        json.RawMessage `json:"participant_attributes"`
	ParticipantAttributesContext *string         `json:"participant_attributes_context"`
	ParticipantAttributesType    *string         `json:"participant_attributes_type"`
}

// Inserts or refreshes a participant row for the given contract.
func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) error {
	_, err := q.db.Exec(ctx, upsertParticipant,
		arg.ID,
		arg.ContractID,
		arg.DescriptorName,
		arg.ParticipantAttributes,
		arg.ParticipantAttributesContext,
		arg.ParticipantAttributesType,
	)
	return err
}

const upsertPerformance = `-- name: UpsertPerformance :exec
INSERT INTO contract_performances (
    id,
    contract_id,
    status_code,
    commitment_ids,
    performance_attributes,
    performance_attributes_context,
    performance_attributes_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id, contract_id)
    DO UPDATE SET
        status_code                     = EXCLUDED.status_code,
        commitment_ids                  = EXCLUDED.commitment_ids,
        performance_attributes          = EXCLUDED.performance_attributes,
        performance_attributes_context  = EXCLUDED.performance_attributes_context,
        performance_attributes_type     = EXCLUDED.performance_attributes_type,
        updated_at                      = NOW()
`

type UpsertPerformanceParams struct {
	ID                           string          `json:"id"`
	ContractID                   uuid.UUID       `json:"contract_id"`
	StatusCode                   *string         `json:"status_code"`
	CommitmentIds                []string        `json:"commitment_ids"`
	PerformanceAttributes        json.RawMessage `json:"performance_attributes"`
	PerformanceAttributesContext *string         `json:"performance_attributes_context"`
	PerformanceAttributesType    *string         `json:"performance_attributes_type"`
}

// Inserts or refreshes a performance (fulfillment) unit for the contract.
func (q *Queries) UpsertPerformance(ctx context.Context, arg UpsertPerformanceParams) error {
	_, err := q.db.Exec(ctx, upsertPerformance,
		arg.ID,
		arg.ContractID,
		arg.StatusCode,
		arg.CommitmentIds,
		arg.PerformanceAttributes,
		arg.PerformanceAttributesContext,
		arg.PerformanceAttributesType,
	)
	return err
}
