// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AckStatus string

const (
	AckStatusACK  AckStatus = "ACK"
	AckStatusNACK AckStatus = "NACK"
)

func (e *AckStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AckStatus(s)
	case string:
		*e = AckStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AckStatus: %T", src)
	}
	return nil
}

type NullAckStatus struct {
	AckStatus AckStatus `json:"ack_status"`
	Valid     bool      `json:"valid"` // Valid is true if AckStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAckStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AckStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AckStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAckStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AckStatus), nil
}

type BecknAction string

const (
	BecknActionDiscover            BecknAction = "discover"
	BecknActionOnDiscover          BecknAction = "on_discover"
	BecknActionSelect              BecknAction = "select"
	BecknActionOnSelect            BecknAction = "on_select"
	BecknActionInit                BecknAction = "init"
	BecknActionOnInit              BecknAction = "on_init"
	BecknActionConfirm             BecknAction = "confirm"
	BecknActionOnConfirm           BecknAction = "on_confirm"
	BecknActionStatus              BecknAction = "status"
	BecknActionOnStatus            BecknAction = "on_status"
	BecknActionTrack               BecknAction = "track"
	BecknActionOnTrack             BecknAction = "on_track"
	BecknActionUpdate              BecknAction = "update"
	BecknActionOnUpdate            BecknAction = "on_update"
	BecknActionCancel              BecknAction = "cancel"
	BecknActionOnCancel            BecknAction = "on_cancel"
	BecknActionRate                BecknAction = "rate"
	BecknActionOnRate              BecknAction = "on_rate"
	BecknActionSupport             BecknAction = "support"
	BecknActionOnSupport           BecknAction = "on_support"
	BecknActionCatalogPublish      BecknAction = "catalog_publish"
	BecknActionCatalogOnPublish    BecknAction = "catalog_on_publish"
	BecknActionCatalogSubscription BecknAction = "catalog_subscription"
	BecknActionCatalogPull         BecknAction = "catalog_pull"
)

func (e *BecknAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BecknAction(s)
	case string:
		*e = BecknAction(s)
	default:
		return fmt.Errorf("unsupported scan type for BecknAction: %T", src)
	}
	return nil
}

type NullBecknAction struct {
	BecknAction BecknAction `json:"beckn_action"`
	Valid       bool        `json:"valid"` // Valid is true if BecknAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBecknAction) Scan(value interface{}) error {
	if value == nil {
		ns.BecknAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BecknAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBecknAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BecknAction), nil
}

type CatalogType string

const (
	CatalogTypeMaster  CatalogType = "master"
	CatalogTypeRegular CatalogType = "regular"
)

func (e *CatalogType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogType(s)
	case string:
		*e = CatalogType(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogType: %T", src)
	}
	return nil
}

type NullCatalogType struct {
	CatalogType CatalogType `json:"catalog_type"`
	Valid       bool        `json:"valid"` // Valid is true if CatalogType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogType) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogType), nil
}

type CatalogUpdateMode string

const (
	CatalogUpdateModeFULL  CatalogUpdateMode = "FULL"
	CatalogUpdateModeMERGE CatalogUpdateMode = "MERGE"
)

func (e *CatalogUpdateMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogUpdateMode(s)
	case string:
		*e = CatalogUpdateMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogUpdateMode: %T", src)
	}
	return nil
}

type NullCatalogUpdateMode struct {
	CatalogUpdateMode CatalogUpdateMode `json:"catalog_update_mode"`
	Valid             bool              `json:"valid"` // Valid is true if CatalogUpdateMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogUpdateMode) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogUpdateMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogUpdateMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogUpdateMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogUpdateMode), nil
}

type CommitmentStatus string

const (
	CommitmentStatusDRAFT  CommitmentStatus = "DRAFT"
	CommitmentStatusACTIVE CommitmentStatus = "ACTIVE"
	CommitmentStatusCLOSED CommitmentStatus = "CLOSED"
)

func (e *CommitmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommitmentStatus(s)
	case string:
		*e = CommitmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommitmentStatus: %T", src)
	}
	return nil
}

type NullCommitmentStatus struct {
	CommitmentStatus CommitmentStatus `json:"commitment_status"`
	Valid            bool             `json:"valid"` // Valid is true if CommitmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommitmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommitmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommitmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommitmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommitmentStatus), nil
}

type ContractStatus string

const (
	ContractStatusDRAFT     ContractStatus = "DRAFT"
	ContractStatusACTIVE    ContractStatus = "ACTIVE"
	ContractStatusCANCELLED ContractStatus = "CANCELLED"
	ContractStatusCOMPLETE  ContractStatus = "COMPLETE"
)

func (e *ContractStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContractStatus(s)
	case string:
		*e = ContractStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContractStatus: %T", src)
	}
	return nil
}

type NullContractStatus struct {
	ContractStatus ContractStatus `json:"contract_status"`
	Valid          bool           `json:"valid"` // Valid is true if ContractStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContractStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContractStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContractStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContractStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContractStatus), nil
}

type MessageDirection string

const (
	MessageDirectionINBOUND  MessageDirection = "INBOUND"
	MessageDirectionOUTBOUND MessageDirection = "OUTBOUND"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection `json:"message_direction"`
	Valid            bool             `json:"valid"` // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING      OutboxStatus = "PENDING"
	OutboxStatusPROCESSING   OutboxStatus = "PROCESSING"
	OutboxStatusDELIVERED    OutboxStatus = "DELIVERED"
	OutboxStatusFAILED       OutboxStatus = "FAILED"
	OutboxStatusDEADLETTERED OutboxStatus = "DEAD_LETTERED"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type SettlementStatus string

const (
	SettlementStatusDRAFT     SettlementStatus = "DRAFT"
	SettlementStatusCOMMITTED SettlementStatus = "COMMITTED"
	SettlementStatusCOMPLETE  SettlementStatus = "COMPLETE"
)

func (e *SettlementStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SettlementStatus(s)
	case string:
		*e = SettlementStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SettlementStatus: %T", src)
	}
	return nil
}

type NullSettlementStatus struct {
	SettlementStatus SettlementStatus `json:"settlement_status"`
	Valid            bool             `json:"valid"` // Valid is true if SettlementStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSettlementStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SettlementStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SettlementStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSettlementStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SettlementStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusACTIVE   SubscriptionStatus = "ACTIVE"
	SubscriptionStatusINACTIVE SubscriptionStatus = "INACTIVE"
	SubscriptionStatusDELETED  SubscriptionStatus = "DELETED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type SupportTicketStatus string

const (
	SupportTicketStatusOPEN       SupportTicketStatus = "OPEN"
	SupportTicketStatusINPROGRESS SupportTicketStatus = "IN_PROGRESS"
	SupportTicketStatusRESOLVED   SupportTicketStatus = "RESOLVED"
	SupportTicketStatusCLOSED     SupportTicketStatus = "CLOSED"
)

func (e *SupportTicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SupportTicketStatus(s)
	case string:
		*e = SupportTicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SupportTicketStatus: %T", src)
	}
	return nil
}

type NullSupportTicketStatus struct {
	SupportTicketStatus SupportTicketStatus `json:"support_ticket_status"`
	Valid               bool                `json:"valid"` // Valid is true if SupportTicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSupportTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SupportTicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SupportTicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSupportTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SupportTicketStatus), nil
}

type TrackingStatus string

const (
	TrackingStatusACTIVE   TrackingStatus = "ACTIVE"
	TrackingStatusINACTIVE TrackingStatus = "INACTIVE"
)

func (e *TrackingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackingStatus(s)
	case string:
		*e = TrackingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackingStatus: %T", src)
	}
	return nil
}

type NullTrackingStatus struct {
	TrackingStatus TrackingStatus `json:"tracking_status"`
	Valid          bool           `json:"valid"` // Valid is true if TrackingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TrackingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackingStatus), nil
}

// Immutable, partitioned audit log of all Beckn protocol messages. Provides non-repudiation — never update or delete rows.
type BecknMessageLog struct {
	ID            uuid.UUID        `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	MessageID     uuid.UUID        `json:"message_id"`
	Action        BecknAction      `json:"action"`
	Direction     MessageDirection `json:"direction"`
	BapID         *string          `json:"bap_id"`
	BapUri        *string          `json:"bap_uri"`
	BppID         *string          `json:"bpp_id"`
	BppUri        *string          `json:"bpp_uri"`
	NetworkID     *string          `json:"network_id"`
	Domain        *string          `json:"domain"`
	AckStatus     NullAckStatus    `json:"ack_status"`
	// Full JSON request body. Enables replay and dispute resolution.
	RequestPayload       json.RawMessage `json:"request_payload"`
	ResponsePayload      json.RawMessage `json:"response_payload"`
	ErrorCode            *string         `json:"error_code"`
	ErrorMessage         *string         `json:"error_message"`
	ProcessingDurationMs *int32          `json:"processing_duration_ms"`
	// Raw Authorization header value for signature re-verification.
	RequestSignature *string            `json:"request_signature"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Url              *string            `json:"url"`
}

// Canonical BPP subscriber identities. bpp_id is the unique subscriber ID as registered on dedi.global.
type BppIdentity struct {
	BppID        string             `json:"bpp_id"`
	BppUri       string             `json:"bpp_uri"`
	NetworkIds   []string           `json:"network_ids"`
	Domains      []string           `json:"domains"`
	IsActive     bool               `json:"is_active"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Ed25519 signing key registry for each BPP. Supports zero-downtime key rotation. Multiple keys may be active simultaneously during transition windows.
type BppSigningKey struct {
	ID    uuid.UUID `json:"id"`
	BppID string    `json:"bpp_id"`
	// The uniqueKeyId segment in the Signature keyId: {bppId}|{uniqueKeyId}|ed25519
	KeyID               string             `json:"key_id"`
	SigningPublicKey    string             `json:"signing_public_key"`
	EncryptionPublicKey *string            `json:"encryption_public_key"`
	IsActive            bool               `json:"is_active"`
	ValidFrom           pgtype.Timestamptz `json:"valid_from"`
	ValidUntil          pgtype.Timestamptz `json:"valid_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Beckn Catalog objects published by the BPP. Versioned — each publish call increments version.
type Catalog struct {
	ID                       string             `json:"id"`
	BppID                    string             `json:"bpp_id"`
	BppUri                   string             `json:"bpp_uri"`
	ProviderID               string             `json:"provider_id"`
	DescriptorName           string             `json:"descriptor_name"`
	DescriptorCode           *string            `json:"descriptor_code"`
	DescriptorShortDesc      *string            `json:"descriptor_short_desc"`
	DescriptorLongDesc       *string            `json:"descriptor_long_desc"`
	DescriptorThumbnailImage *string            `json:"descriptor_thumbnail_image"`
	DescriptorDocs           json.RawMessage    `json:"descriptor_docs"`
	DescriptorMediaFiles     json.RawMessage    `json:"descriptor_media_files"`
	IsActive                 bool               `json:"is_active"`
	CatalogType              NullCatalogType    `json:"catalog_type"`
	UpdateMode               CatalogUpdateMode  `json:"update_mode"`
	ValidityStart            pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd              pgtype.Timestamptz `json:"validity_end"`
	Version                  int32              `json:"version"`
	// Array of JSON-LD context URIs for the schemas used by resources in this catalog.
	SchemaContext json.RawMessage    `json:"schema_context"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

// Processing results returned by the CDS for each catalog publish attempt.
type CatalogPublishResult struct {
	ID             uuid.UUID          `json:"id"`
	CatalogID      string             `json:"catalog_id"`
	BppID          string             `json:"bpp_id"`
	CatalogVersion int32              `json:"catalog_version"`
	Status         string             `json:"status"`
	Errors         json.RawMessage    `json:"errors"`
	Stats          json.RawMessage    `json:"stats"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

// BAP subscriptions to catalog update events. Drives which on_discover callbacks are pushed when catalogs are published or updated.
type CatalogSubscription struct {
	ID           uuid.UUID `json:"id"`
	SubscriberID string    `json:"subscriber_id"`
	BapID        string    `json:"bap_id"`
	BapUri       string    `json:"bap_uri"`
	NetworkIds   []string  `json:"network_ids"`
	// JSON-LD schema type URIs for filtering. Empty array is treated as wildcard.
	SchemaTypes []string           `json:"schema_types"`
	CallbackUrl string             `json:"callback_url"`
	Status      SubscriptionStatus `json:"status"`
	// Retry and timeout policy per Beckn DeliveryPolicy schema.
	DeliveryPolicy json.RawMessage    `json:"delivery_policy"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Structured sub-agreements within a Contract. Each commitment binds resources to an offer.
type Commitment struct {
	ID                          string             `json:"id"`
	ContractID                  uuid.UUID          `json:"contract_id"`
	Status                      CommitmentStatus   `json:"status"`
	CommitmentAttributes        json.RawMessage    `json:"commitment_attributes"`
	CommitmentAttributesContext *string            `json:"commitment_attributes_context"`
	CommitmentAttributesType    *string            `json:"commitment_attributes_type"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

// The single Offer selected for a commitment. Stored as a snapshot to preserve agreed terms.
type CommitmentOffer struct {
	ID              uuid.UUID          `json:"id"`
	CommitmentID    string             `json:"commitment_id"`
	ContractID      uuid.UUID          `json:"contract_id"`
	OfferID         string             `json:"offer_id"`
	OfferDescriptor json.RawMessage    `json:"offer_descriptor"`
	OfferAttributes json.RawMessage    `json:"offer_attributes"`
	ResourceIds     []string           `json:"resource_ids"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Resources selected within a commitment. Quantity is domain-agnostic JSONB.
type CommitmentResource struct {
	ID                 uuid.UUID          `json:"id"`
	CommitmentID       string             `json:"commitment_id"`
	ContractID         uuid.UUID          `json:"contract_id"`
	ResourceID         string             `json:"resource_id"`
	ResourceDescriptor json.RawMessage    `json:"resource_descriptor"`
	ResourceAttributes json.RawMessage    `json:"resource_attributes"`
	Quantity           json.RawMessage    `json:"quantity"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Value promised to be exchanged under a Contract. Use PriceSpecification attributes for monetary; generic Attributes for other types.
type Consideration struct {
	ID                             string             `json:"id"`
	ContractID                     uuid.UUID          `json:"contract_id"`
	StatusCode                     string             `json:"status_code"`
	StatusName                     *string            `json:"status_name"`
	ConsiderationAttributes        json.RawMessage    `json:"consideration_attributes"`
	ConsiderationAttributesContext *string            `json:"consideration_attributes_context"`
	ConsiderationAttributesType    *string            `json:"consideration_attributes_type"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
}

// Beckn Contract — the central transaction object binding commitments, consideration, performance, settlements, and participants across the full protocol lifecycle.
type Contract struct {
	ID     uuid.UUID `json:"id"`
	BppID  string    `json:"bpp_id"`
	BapID  string    `json:"bap_id"`
	BapUri string    `json:"bap_uri"`
	// Persists across discover→confirm for a single user session (from Context.transactionId).
	TransactionID        uuid.UUID       `json:"transaction_id"`
	NetworkID            *string         `json:"network_id"`
	Domain               *string         `json:"domain"`
	Status               ContractStatus  `json:"status"`
	DescriptorName       *string         `json:"descriptor_name"`
	DescriptorCode       *string         `json:"descriptor_code"`
	DescriptorShortDesc  *string         `json:"descriptor_short_desc"`
	DescriptorLongDesc   *string         `json:"descriptor_long_desc"`
	DescriptorDocs       json.RawMessage `json:"descriptor_docs"`
	DescriptorMediaFiles json.RawMessage `json:"descriptor_media_files"`
	// JSON-LD extension attributes for domain-specific contract data. Must carry @context and @type when populated.
	ContractAttributes        json.RawMessage    `json:"contract_attributes"`
	ContractAttributesContext *string            `json:"contract_attributes_context"`
	ContractAttributesType    *string            `json:"contract_attributes_type"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

// Parties involved in a Contract. Role is expressed via participant_attributes @type.
type ContractParticipant struct {
	ID                           string             `json:"id"`
	ContractID                   uuid.UUID          `json:"contract_id"`
	DescriptorName               *string            `json:"descriptor_name"`
	DescriptorCode               *string            `json:"descriptor_code"`
	DescriptorShortDesc          *string            `json:"descriptor_short_desc"`
	DescriptorLongDesc           *string            `json:"descriptor_long_desc"`
	ParticipantAttributes        json.RawMessage    `json:"participant_attributes"`
	ParticipantAttributesContext *string            `json:"participant_attributes_context"`
	ParticipantAttributesType    *string            `json:"participant_attributes_type"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

// Generalized fulfillment execution units for a Contract. Each row represents one delivery/service/activation plan. Tracking and support interactions link here.
type ContractPerformance struct {
	ID              string    `json:"id"`
	ContractID      uuid.UUID `json:"contract_id"`
	StatusCode      *string   `json:"status_code"`
	StatusName      *string   `json:"status_name"`
	StatusShortDesc *string   `json:"status_short_desc"`
	// IDs of commitments being executed by this performance unit.
	CommitmentIds                []string           `json:"commitment_ids"`
	PerformanceAttributes        json.RawMessage    `json:"performance_attributes"`
	PerformanceAttributesContext *string            `json:"performance_attributes_context"`
	PerformanceAttributesType    *string            `json:"performance_attributes_type"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

// Real-time tracking handles for active contract fulfillment. Not for contract state changes (use on_status for that).
type ContractTracking struct {
	ID                        uuid.UUID          `json:"id"`
	ContractID                uuid.UUID          `json:"contract_id"`
	PerformanceID             *string            `json:"performance_id"`
	Status                    TrackingStatus     `json:"status"`
	Url                       string             `json:"url"`
	TrackingAttributes        json.RawMessage    `json:"tracking_attributes"`
	TrackingAttributesContext *string            `json:"tracking_attributes_context"`
	TrackingAttributesType    *string            `json:"tracking_attributes_type"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

// Beckn callbacks that exhausted the retry budget. Requires manual review and replay by the operations team.
type DeadLetterEvent struct {
	ID             uuid.UUID          `json:"id"`
	OutboxEventID  uuid.UUID          `json:"outbox_event_id"`
	Action         BecknAction        `json:"action"`
	TransactionID  pgtype.UUID        `json:"transaction_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	TargetUrl      string             `json:"target_url"`
	BapID          *string            `json:"bap_id"`
	Payload        json.RawMessage    `json:"payload"`
	TotalAttempts  int32              `json:"total_attempts"`
	LastError      *string            `json:"last_error"`
	ContractID     pgtype.UUID        `json:"contract_id"`
	Reviewed       bool               `json:"reviewed"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy     *string            `json:"reviewed_by"`
	ResolutionNote *string            `json:"resolution_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Beckn Offer entities. Defines the terms and value proposition for committing one or more resources.
type Offer struct {
	ID                       string             `json:"id"`
	CatalogID                string             `json:"catalog_id"`
	BppID                    string             `json:"bpp_id"`
	ProviderID               *string            `json:"provider_id"`
	DescriptorName           *string            `json:"descriptor_name"`
	DescriptorCode           *string            `json:"descriptor_code"`
	DescriptorShortDesc      *string            `json:"descriptor_short_desc"`
	DescriptorLongDesc       *string            `json:"descriptor_long_desc"`
	DescriptorThumbnailImage *string            `json:"descriptor_thumbnail_image"`
	DescriptorDocs           json.RawMessage    `json:"descriptor_docs"`
	DescriptorMediaFiles     json.RawMessage    `json:"descriptor_media_files"`
	ResourceIds              []string           `json:"resource_ids"`
	AddOns                   json.RawMessage    `json:"add_ons"`
	OfferAttributes          json.RawMessage    `json:"offer_attributes"`
	OfferAttributesContext   *string            `json:"offer_attributes_context"`
	OfferAttributesType      *string            `json:"offer_attributes_type"`
	ValidityStart            pgtype.Timestamptz `json:"validity_start"`
	ValidityEnd              pgtype.Timestamptz `json:"validity_end"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `json:"deleted_at"`
}

// Visibility constraints on an Offer. When absent the offer is visible to all network participants.
type OfferAvailableTo struct {
	ID        uuid.UUID `json:"id"`
	OfferID   string    `json:"offer_id"`
	CatalogID string    `json:"catalog_id"`
	BppID     string    `json:"bpp_id"`
	ScopeType string    `json:"scope_type"`
	ScopeID   string    `json:"scope_id"`
}

// Proposed value exchange terms attached to an Offer (price, credits, service exchange, etc.).
type OfferConsideration struct {
	ID                             uuid.UUID       `json:"id"`
	OfferID                        string          `json:"offer_id"`
	CatalogID                      string          `json:"catalog_id"`
	BppID                          string          `json:"bpp_id"`
	ConsiderationID                string          `json:"consideration_id"`
	StatusCode                     string          `json:"status_code"`
	StatusName                     *string         `json:"status_name"`
	ConsiderationAttributes        json.RawMessage `json:"consideration_attributes"`
	ConsiderationAttributesContext *string         `json:"consideration_attributes_context"`
	ConsiderationAttributesType    *string         `json:"consideration_attributes_type"`
}

// Transactional outbox for reliable Beckn callback delivery. Written in the same transaction as state changes; consumed by the async delivery worker.
type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	Action        BecknAction     `json:"action"`
	TransactionID pgtype.UUID     `json:"transaction_id"`
	MessageID     uuid.UUID       `json:"message_id"`
	TargetUrl     string          `json:"target_url"`
	BapID         *string         `json:"bap_id"`
	BapUri        *string         `json:"bap_uri"`
	Payload       json.RawMessage `json:"payload"`
	Status        OutboxStatus    `json:"status"`
	AttemptCount  int32           `json:"attempt_count"`
	MaxAttempts   int32           `json:"max_attempts"`
	// Earliest time the worker should next attempt delivery. Backoff is applied by the worker after each failure.
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	LastError       *string            `json:"last_error"`
	ContractID      pgtype.UUID        `json:"contract_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Beckn Provider entities. Each provider belongs to one BPP and may appear in multiple catalogs.
type Provider struct {
	ID                       string          `json:"id"`
	BppID                    string          `json:"bpp_id"`
	DescriptorName           string          `json:"descriptor_name"`
	DescriptorCode           *string         `json:"descriptor_code"`
	DescriptorShortDesc      *string         `json:"descriptor_short_desc"`
	DescriptorLongDesc       *string         `json:"descriptor_long_desc"`
	DescriptorThumbnailImage *string         `json:"descriptor_thumbnail_image"`
	DescriptorDocs           json.RawMessage `json:"descriptor_docs"`
	DescriptorMediaFiles     json.RawMessage `json:"descriptor_media_files"`
	// JSON-LD attributes bag for domain-specific provider extensions. Must include @context and @type.
	ProviderAttributes        json.RawMessage    `json:"provider_attributes"`
	ProviderAttributesContext *string            `json:"provider_attributes_context"`
	ProviderAttributesType    *string            `json:"provider_attributes_type"`
	IsActive                  bool               `json:"is_active"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `json:"deleted_at"`
}

// Physical locations where a provider operates. Maps to Provider.availableAt[].
type ProviderLocation struct {
	ID         uuid.UUID `json:"id"`
	ProviderID string    `json:"provider_id"`
	BppID      string    `json:"bpp_id"`
	// Full GeoJSON geometry object (RFC 7946). Type and coordinates are stored verbatim.
	Geo               json.RawMessage    `json:"geo"`
	AddressStreet     *string            `json:"address_street"`
	AddressLocality   *string            `json:"address_locality"`
	AddressRegion     *string            `json:"address_region"`
	AddressCountry    *string            `json:"address_country"`
	AddressPostalCode *string            `json:"address_postal_code"`
	AddressExtended   *string            `json:"address_extended"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Rating inputs from BAPs for any ratable entity within a completed contract.
type Rating struct {
	ID               uuid.UUID       `json:"id"`
	ContractID       uuid.UUID       `json:"contract_id"`
	BapID            string          `json:"bap_id"`
	BapUri           string          `json:"bap_uri"`
	TargetID         string          `json:"target_id"`
	TargetDescriptor json.RawMessage `json:"target_descriptor"`
	TargetAttributes json.RawMessage `json:"target_attributes"`
	// Score expressed as JSONB (min, max, value) to support any rating scale.
	Range json.RawMessage `json:"range"`
	// Serialized FormSubmission including form URI, submission ID, and field responses.
	FeedbackFormSubmission json.RawMessage    `json:"feedback_form_submission"`
	IsPreview              bool               `json:"is_preview"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

// Beckn Resource entities. Domain-neutral unit of value discoverable and committable on the network.
type Resource struct {
	ID                       string          `json:"id"`
	CatalogID                string          `json:"catalog_id"`
	BppID                    string          `json:"bpp_id"`
	DescriptorName           *string         `json:"descriptor_name"`
	DescriptorCode           *string         `json:"descriptor_code"`
	DescriptorShortDesc      *string         `json:"descriptor_short_desc"`
	DescriptorLongDesc       *string         `json:"descriptor_long_desc"`
	DescriptorThumbnailImage *string         `json:"descriptor_thumbnail_image"`
	DescriptorDocs           json.RawMessage `json:"descriptor_docs"`
	DescriptorMediaFiles     json.RawMessage `json:"descriptor_media_files"`
	// JSON-LD attributes bag. MUST contain @context and @type per the Beckn Attributes schema.
	ResourceAttributes        json.RawMessage `json:"resource_attributes"`
	ResourceAttributesContext *string         `json:"resource_attributes_context"`
	ResourceAttributesType    *string         `json:"resource_attributes_type"`
	MasterResourceID          *string         `json:"master_resource_id"`
	// PostgreSQL tsvector for full-text search across name, shortDesc, longDesc, and attributes. Updated automatically by trigger on insert/update.
	SearchVector string             `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// Discharge records for consideration agreed in a Contract. Carries payment gateway references or other proof of value transfer.
type Settlement struct {
	ID                          string             `json:"id"`
	ContractID                  uuid.UUID          `json:"contract_id"`
	ConsiderationID             string             `json:"consideration_id"`
	Status                      SettlementStatus   `json:"status"`
	SettlementAttributes        json.RawMessage    `json:"settlement_attributes"`
	SettlementAttributesContext *string            `json:"settlement_attributes_context"`
	SettlementAttributesType    *string            `json:"settlement_attributes_type"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

// Support tickets raised by BAPs against contracts or other entities. Channels carry JSON-LD contact descriptors (email, phone, chat, etc.).
type SupportTicket struct {
	ID                  uuid.UUID           `json:"id"`
	ContractID          pgtype.UUID         `json:"contract_id"`
	BapID               string              `json:"bap_id"`
	BapUri              string              `json:"bap_uri"`
	DescriptorName      *string             `json:"descriptor_name"`
	DescriptorCode      *string             `json:"descriptor_code"`
	DescriptorShortDesc *string             `json:"descriptor_short_desc"`
	DescriptorLongDesc  *string             `json:"descriptor_long_desc"`
	Channels            json.RawMessage     `json:"channels"`
	Status              SupportTicketStatus `json:"status"`
	ResolvedAt          pgtype.Timestamptz  `json:"resolved_at"`
	IsPreview           bool                `json:"is_preview"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
}
