// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select.sql

package sqlc

import (
	"context"
)

const getOffer = `-- name: GetOffer :one

SELECT id, catalog_id, bpp_id, provider_id, descriptor_name, descriptor_code, descriptor_short_desc, descriptor_long_desc, descriptor_thumbnail_image, descriptor_docs, descriptor_media_files, resource_ids, add_ons, offer_attributes, offer_attributes_context, offer_attributes_type, validity_start, validity_end, created_at, updated_at, deleted_at FROM offers
WHERE id = $1 AND bpp_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetOfferParams struct {
	ID    string `json:"id"`
	BppID string `json:"bpp_id"`
}

// Queries for the /beckn/select handler.
// Used to look up offers and resources from the published catalog inventory.
// Finds an active offer by ID within this BPP.
// Returns the first match (offer IDs should be unique within a BPP).
func (q *Queries) GetOffer(ctx context.Context, arg GetOfferParams) (Offer, error) {
	row := q.db.QueryRow(ctx, getOffer, arg.ID, arg.BppID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.BppID,
		&i.ProviderID,
		&i.DescriptorName,
		&i.DescriptorCode,
		&i.DescriptorShortDesc,
		&i.DescriptorLongDesc,
		&i.DescriptorThumbnailImage,
		&i.DescriptorDocs,
		&i.DescriptorMediaFiles,
		&i.ResourceIds,
		&i.AddOns,
		&i.OfferAttributes,
		&i.OfferAttributesContext,
		&i.OfferAttributesType,
		&i.ValidityStart,
		&i.ValidityEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOfferConsiderations = `-- name: GetOfferConsiderations :many
SELECT id, offer_id, catalog_id, bpp_id, consideration_id, status_code, status_name, consideration_attributes, consideration_attributes_context, consideration_attributes_type FROM offer_considerations
WHERE offer_id = $1 AND bpp_id = $2
`

type GetOfferConsiderationsParams struct {
	OfferID string `json:"offer_id"`
	BppID   string `json:"bpp_id"`
}

// Returns all active pricing records for an offer.
func (q *Queries) GetOfferConsiderations(ctx context.Context, arg GetOfferConsiderationsParams) ([]OfferConsideration, error) {
	rows, err := q.db.Query(ctx, getOfferConsiderations, arg.OfferID, arg.BppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfferConsideration{}
	for rows.Next() {
		var i OfferConsideration
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.CatalogID,
			&i.BppID,
			&i.ConsiderationID,
			&i.StatusCode,
			&i.StatusName,
			&i.ConsiderationAttributes,
			&i.ConsiderationAttributesContext,
			&i.ConsiderationAttributesType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT id, catalog_id, bpp_id, descriptor_name, descriptor_code, descriptor_short_desc, descriptor_long_desc, descriptor_thumbnail_image, descriptor_docs, descriptor_media_files, resource_attributes, resource_attributes_context, resource_attributes_type, master_resource_id, search_vector, created_at, updated_at, deleted_at FROM resources
WHERE id = $1 AND bpp_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetResourceParams struct {
	ID    string `json:"id"`
	BppID string `json:"bpp_id"`
}

// Finds an active resource (product/service) by ID within this BPP.
func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ID, arg.BppID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CatalogID,
		&i.BppID,
		&i.DescriptorName,
		&i.DescriptorCode,
		&i.DescriptorShortDesc,
		&i.DescriptorLongDesc,
		&i.DescriptorThumbnailImage,
		&i.DescriptorDocs,
		&i.DescriptorMediaFiles,
		&i.ResourceAttributes,
		&i.ResourceAttributesContext,
		&i.ResourceAttributesType,
		&i.MasterResourceID,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
