// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementResourceStock = `-- name: DecrementResourceStock :exec
UPDATE resource_stock
SET quantity   = GREATEST(0, quantity - 1),
    sold       = sold + 1,
    updated_at = NOW()
WHERE resource_id = $1
  AND bpp_id      = $2
`

type DecrementResourceStockParams struct {
	ResourceID string `json:"resource_id"`
	BppID      string `json:"bpp_id"`
}

// Called on successful confirm to move one unit from available to sold.
// Uses GREATEST(0, …) to prevent the counter going negative if called twice.
func (q *Queries) DecrementResourceStock(ctx context.Context, arg DecrementResourceStockParams) error {
	_, err := q.db.Exec(ctx, decrementResourceStock, arg.ResourceID, arg.BppID)
	return err
}

const listResourceStock = `-- name: ListResourceStock :many
SELECT
    rs.resource_id,
    rs.bpp_id,
    rs.quantity,
    rs.sold,
    rs.updated_at,
    r.descriptor_name,
    r.catalog_id
FROM resource_stock rs
LEFT JOIN resources r
       ON r.id     = rs.resource_id
      AND r.bpp_id = rs.bpp_id
WHERE rs.bpp_id = $1
ORDER BY rs.updated_at DESC
`

type ListResourceStockRow struct {
	ResourceID     string             `json:"resource_id"`
	BppID          string             `json:"bpp_id"`
	Quantity       int32              `json:"quantity"`
	Sold           int32              `json:"sold"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DescriptorName *string            `json:"descriptor_name"`
	CatalogID      *string            `json:"catalog_id"`
}

// Full stock listing for the dashboard, joined with the resource descriptor.
func (q *Queries) ListResourceStock(ctx context.Context, bppID string) ([]ListResourceStockRow, error) {
	rows, err := q.db.Query(ctx, listResourceStock, bppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourceStockRow{}
	for rows.Next() {
		var i ListResourceStockRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.BppID,
			&i.Quantity,
			&i.Sold,
			&i.UpdatedAt,
			&i.DescriptorName,
			&i.CatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertResourceStock = `-- name: UpsertResourceStock :exec

INSERT INTO resource_stock (resource_id, bpp_id, quantity, sold, updated_at)
VALUES ($1, $2, $3, 0, NOW())
ON CONFLICT (resource_id, bpp_id)
DO UPDATE SET
    quantity   = EXCLUDED.quantity,
    updated_at = NOW()
`

type UpsertResourceStockParams struct {
	ResourceID string `json:"resource_id"`
	BppID      string `json:"bpp_id"`
	Quantity   int32  `json:"quantity"`
}

// Stock management queries for resource_stock table.
// Called during catalog publish to set initial (or updated) stock quantity.
func (q *Queries) UpsertResourceStock(ctx context.Context, arg UpsertResourceStockParams) error {
	_, err := q.db.Exec(ctx, upsertResourceStock, arg.ResourceID, arg.BppID, arg.Quantity)
	return err
}
