// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bap.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessageLog = `-- name: InsertMessageLog :exec
INSERT INTO beckn_message_log (
    transaction_id, message_id,
    action, direction,
    url,
    bap_id, bap_uri,
    bpp_id, bpp_uri, network_id,
    ack_status,
    request_payload, response_payload,
    error_message,
    processing_duration_ms
) VALUES (
    $1, $2,
    $3, $4,
    $5,
    $6, $7,
    $8, $9, $10,
    $11,
    $12, $13,
    $14,
    $15
)
`

type InsertMessageLogParams struct {
	TransactionID        pgtype.UUID      `json:"transaction_id"`
	MessageID            uuid.UUID        `json:"message_id"`
	Action               BecknAction      `json:"action"`
	Direction            MessageDirection `json:"direction"`
	Url                  *string          `json:"url"`
	BapID                *string          `json:"bap_id"`
	BapUri               *string          `json:"bap_uri"`
	BppID                *string          `json:"bpp_id"`
	BppUri               *string          `json:"bpp_uri"`
	NetworkID            *string          `json:"network_id"`
	AckStatus            NullAckStatus    `json:"ack_status"`
	RequestPayload       json.RawMessage  `json:"request_payload"`
	ResponsePayload      json.RawMessage  `json:"response_payload"`
	ErrorMessage         *string          `json:"error_message"`
	ProcessingDurationMs *int32           `json:"processing_duration_ms"`
}

func (q *Queries) InsertMessageLog(ctx context.Context, arg InsertMessageLogParams) error {
	_, err := q.db.Exec(ctx, insertMessageLog,
		arg.TransactionID,
		arg.MessageID,
		arg.Action,
		arg.Direction,
		arg.Url,
		arg.BapID,
		arg.BapUri,
		arg.BppID,
		arg.BppUri,
		arg.NetworkID,
		arg.AckStatus,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.ErrorMessage,
		arg.ProcessingDurationMs,
	)
	return err
}

const upsertBAPIdentity = `-- name: UpsertBAPIdentity :exec

INSERT INTO bap_identities (bap_id, bap_uri, network_ids, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (bap_id) DO UPDATE SET
    bap_uri     = EXCLUDED.bap_uri,
    network_ids = EXCLUDED.network_ids,
    updated_at  = NOW()
`

type UpsertBAPIdentityParams struct {
	BapID      string   `json:"bap_id"`
	BapUri     string   `json:"bap_uri"`
	NetworkIds []string `json:"network_ids"`
}

// BAP infrastructure queries: identity seeding and message audit logging.
func (q *Queries) UpsertBAPIdentity(ctx context.Context, arg UpsertBAPIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertBAPIdentity, arg.BapID, arg.BapUri, arg.NetworkIds)
	return err
}
