// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AckStatus string

const (
	AckStatusACK  AckStatus = "ACK"
	AckStatusNACK AckStatus = "NACK"
)

func (e *AckStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AckStatus(s)
	case string:
		*e = AckStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AckStatus: %T", src)
	}
	return nil
}

type NullAckStatus struct {
	AckStatus AckStatus `json:"ack_status"`
	Valid     bool      `json:"valid"` // Valid is true if AckStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAckStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AckStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AckStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAckStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AckStatus), nil
}

type BecknAction string

const (
	BecknActionDiscover   BecknAction = "discover"
	BecknActionOnDiscover BecknAction = "on_discover"
	BecknActionSelect     BecknAction = "select"
	BecknActionOnSelect   BecknAction = "on_select"
	BecknActionInit       BecknAction = "init"
	BecknActionOnInit     BecknAction = "on_init"
	BecknActionConfirm    BecknAction = "confirm"
	BecknActionOnConfirm  BecknAction = "on_confirm"
	BecknActionStatus     BecknAction = "status"
	BecknActionOnStatus   BecknAction = "on_status"
	BecknActionTrack      BecknAction = "track"
	BecknActionOnTrack    BecknAction = "on_track"
	BecknActionUpdate     BecknAction = "update"
	BecknActionOnUpdate   BecknAction = "on_update"
	BecknActionCancel     BecknAction = "cancel"
	BecknActionOnCancel   BecknAction = "on_cancel"
	BecknActionRate       BecknAction = "rate"
	BecknActionOnRate     BecknAction = "on_rate"
	BecknActionSupport    BecknAction = "support"
	BecknActionOnSupport  BecknAction = "on_support"
)

func (e *BecknAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BecknAction(s)
	case string:
		*e = BecknAction(s)
	default:
		return fmt.Errorf("unsupported scan type for BecknAction: %T", src)
	}
	return nil
}

type NullBecknAction struct {
	BecknAction BecknAction `json:"beckn_action"`
	Valid       bool        `json:"valid"` // Valid is true if BecknAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBecknAction) Scan(value interface{}) error {
	if value == nil {
		ns.BecknAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BecknAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBecknAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BecknAction), nil
}

type MessageDirection string

const (
	MessageDirectionINBOUND  MessageDirection = "INBOUND"
	MessageDirectionOUTBOUND MessageDirection = "OUTBOUND"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection `json:"message_direction"`
	Valid            bool             `json:"valid"` // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

type TransactionStatus string

const (
	TransactionStatusSELECTSENT    TransactionStatus = "SELECT_SENT"
	TransactionStatusQUOTERECEIVED TransactionStatus = "QUOTE_RECEIVED"
	TransactionStatusINITSENT      TransactionStatus = "INIT_SENT"
	TransactionStatusINITRECEIVED  TransactionStatus = "INIT_RECEIVED"
	TransactionStatusCONFIRMSENT   TransactionStatus = "CONFIRM_SENT"
	TransactionStatusCONFIRMED     TransactionStatus = "CONFIRMED"
	TransactionStatusCANCELLED     TransactionStatus = "CANCELLED"
	TransactionStatusCOMPLETE      TransactionStatus = "COMPLETE"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

// Registered BAP subscribers. Seeded at startup from BAP_ID / BAP_URI env vars.
type BapIdentity struct {
	BapID      string             `json:"bap_id"`
	BapUri     string             `json:"bap_uri"`
	NetworkIds []string           `json:"network_ids"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Immutable audit log of all Beckn protocol messages received or sent by this BAP.
type BecknMessageLog struct {
	ID                   uuid.UUID          `json:"id"`
	TransactionID        pgtype.UUID        `json:"transaction_id"`
	MessageID            uuid.UUID          `json:"message_id"`
	Action               BecknAction        `json:"action"`
	Direction            MessageDirection   `json:"direction"`
	BapID                *string            `json:"bap_id"`
	BapUri               *string            `json:"bap_uri"`
	BppID                *string            `json:"bpp_id"`
	BppUri               *string            `json:"bpp_uri"`
	NetworkID            *string            `json:"network_id"`
	Url                  *string            `json:"url"`
	AckStatus            NullAckStatus      `json:"ack_status"`
	RequestPayload       json.RawMessage    `json:"request_payload"`
	ResponsePayload      json.RawMessage    `json:"response_payload"`
	ErrorMessage         *string            `json:"error_message"`
	ProcessingDurationMs *int32             `json:"processing_duration_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

// Stores the full contract JSON received from the BPP at each on_* callback. The BAP uses this to track the evolving contract state through the Beckn lifecycle.
type ContractSnapshot struct {
	ID            uuid.UUID   `json:"id"`
	TransactionID uuid.UUID   `json:"transaction_id"`
	Action        BecknAction `json:"action"`
	// The UUID the BPP assigned to the contract (populated from on_init onwards).
	ContractID *string            `json:"contract_id"`
	Contract   json.RawMessage    `json:"contract"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// One row per Beckn transactionId initiated by this BAP. Status advances as select → init → confirm actions progress.
type Transaction struct {
	TransactionID uuid.UUID          `json:"transaction_id"`
	BapID         string             `json:"bap_id"`
	NetworkID     *string            `json:"network_id"`
	BppID         *string            `json:"bpp_id"`
	BppUri        *string            `json:"bpp_uri"`
	Status        TransactionStatus  `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
