// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: state.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getContractSnapshot = `-- name: GetContractSnapshot :one
SELECT id, transaction_id, action, contract_id, contract, created_at, updated_at
FROM contract_snapshots
WHERE transaction_id = $1
  AND action = $2
`

type GetContractSnapshotParams struct {
	TransactionID uuid.UUID   `json:"transaction_id"`
	Action        BecknAction `json:"action"`
}

// Returns the most recent contract snapshot for a (transaction_id, action) pair.
func (q *Queries) GetContractSnapshot(ctx context.Context, arg GetContractSnapshotParams) (ContractSnapshot, error) {
	row := q.db.QueryRow(ctx, getContractSnapshot, arg.TransactionID, arg.Action)
	var i ContractSnapshot
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Action,
		&i.ContractID,
		&i.Contract,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestContractSnapshot = `-- name: GetLatestContractSnapshot :one
SELECT id, transaction_id, action, contract_id, contract, created_at, updated_at
FROM contract_snapshots
WHERE transaction_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Returns the latest snapshot for a transaction (highest priority action).
func (q *Queries) GetLatestContractSnapshot(ctx context.Context, transactionID uuid.UUID) (ContractSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestContractSnapshot, transactionID)
	var i ContractSnapshot
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Action,
		&i.ContractID,
		&i.Contract,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT transaction_id, bap_id, network_id, bpp_id, bpp_uri, status, created_at, updated_at
FROM transactions
WHERE transaction_id = $1
`

// Returns the transaction row for the given transaction UUID.
func (q *Queries) GetTransaction(ctx context.Context, transactionID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, transactionID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.BapID,
		&i.NetworkID,
		&i.BppID,
		&i.BppUri,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContractSnapshot = `-- name: UpsertContractSnapshot :exec
INSERT INTO contract_snapshots (transaction_id, action, contract_id, contract)
VALUES ($1, $2, $3, $4)
ON CONFLICT (transaction_id, action) DO UPDATE SET
    contract_id = EXCLUDED.contract_id,
    contract    = EXCLUDED.contract,
    updated_at  = NOW()
`

type UpsertContractSnapshotParams struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	Action        BecknAction     `json:"action"`
	ContractID    *string         `json:"contract_id"`
	Contract      json.RawMessage `json:"contract"`
}

// Stores (or replaces) the full contract JSON for a given (transaction_id, action).
func (q *Queries) UpsertContractSnapshot(ctx context.Context, arg UpsertContractSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertContractSnapshot,
		arg.TransactionID,
		arg.Action,
		arg.ContractID,
		arg.Contract,
	)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :exec

INSERT INTO transactions (transaction_id, bap_id, network_id, bpp_id, bpp_uri, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (transaction_id) DO UPDATE SET
    bpp_id     = EXCLUDED.bpp_id,
    bpp_uri    = EXCLUDED.bpp_uri,
    status     = EXCLUDED.status,
    updated_at = NOW()
`

type UpsertTransactionParams struct {
	TransactionID uuid.UUID         `json:"transaction_id"`
	BapID         string            `json:"bap_id"`
	NetworkID     *string           `json:"network_id"`
	BppID         *string           `json:"bpp_id"`
	BppUri        *string           `json:"bpp_uri"`
	Status        TransactionStatus `json:"status"`
}

// Queries for persisting contract state received in on_* callbacks.
// Creates or updates the transaction tracking row.
func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) error {
	_, err := q.db.Exec(ctx, upsertTransaction,
		arg.TransactionID,
		arg.BapID,
		arg.NetworkID,
		arg.BppID,
		arg.BppUri,
		arg.Status,
	)
	return err
}
