#!/usr/bin/env bash
# One-time: populate the Secret Manager secrets that terraform/secrets.tf
# creates as empty containers but does not write values into (the Postgres
# password is the only one Terraform generates and writes itself).
#
# Run this AFTER:
#   terraform apply -target=google_secret_manager_secret.this
# and BEFORE the full `terraform apply` — Cloud Run revisions fail to deploy
# if the secret they reference has no version yet.
#
# Usage: PROJECT_ID=remiges-trade ./scripts/seed-secrets.sh
#
# This script is committed to a PUBLIC repo — unlike some reference setups,
# it intentionally has NO baked-in secret defaults. Every value below is
# required via env var and the script fails loudly if any is unset. Source
# the real values from your own local, git-ignored secret store (this
# session's config/local-simple-{bap,bpp}.yaml + root .env hold the current
# sandbox values, if you're seeding a deployment meant to mirror local dev).

set -euo pipefail

PROJECT_ID="${PROJECT_ID:?set PROJECT_ID}"

seed() {
  local name="$1" value="$2"
  printf '%s' "$value" | gcloud secrets versions add "$name" --project="$PROJECT_ID" --data-file=-
}

require() {
  local var_name="$1"
  if [ -z "${!var_name:-}" ]; then
    echo "ERROR: env var ${var_name} is required (no defaults are baked into this script)." >&2
    exit 1
  fi
}

for v in BAP_PRIVATE_KEY BAP_KEY_ID BPP_PRIVATE_KEY BPP_KEY_ID \
         BAP_ONIX_KEY_ID BAP_ONIX_SIGNING_PRIVATE_KEY BAP_ONIX_SIGNING_PUBLIC_KEY \
         BAP_ONIX_ENCR_PRIVATE_KEY BAP_ONIX_ENCR_PUBLIC_KEY \
         BPP_ONIX_KEY_ID BPP_ONIX_SIGNING_PRIVATE_KEY BPP_ONIX_SIGNING_PUBLIC_KEY \
         BPP_ONIX_ENCR_PRIVATE_KEY BPP_ONIX_ENCR_PUBLIC_KEY; do
  require "$v"
done

seed bap-private-key              "$BAP_PRIVATE_KEY"
seed bap-key-id                   "$BAP_KEY_ID"
seed bpp-private-key              "$BPP_PRIVATE_KEY"
seed bpp-key-id                   "$BPP_KEY_ID"
seed bap-onix-key-id              "$BAP_ONIX_KEY_ID"
seed bap-onix-signing-private-key "$BAP_ONIX_SIGNING_PRIVATE_KEY"
seed bap-onix-signing-public-key  "$BAP_ONIX_SIGNING_PUBLIC_KEY"
seed bap-onix-encr-private-key    "$BAP_ONIX_ENCR_PRIVATE_KEY"
seed bap-onix-encr-public-key     "$BAP_ONIX_ENCR_PUBLIC_KEY"
seed bpp-onix-key-id              "$BPP_ONIX_KEY_ID"
seed bpp-onix-signing-private-key "$BPP_ONIX_SIGNING_PRIVATE_KEY"
seed bpp-onix-signing-public-key  "$BPP_ONIX_SIGNING_PUBLIC_KEY"
seed bpp-onix-encr-private-key    "$BPP_ONIX_ENCR_PRIVATE_KEY"
seed bpp-onix-encr-public-key     "$BPP_ONIX_ENCR_PUBLIC_KEY"

echo "done — seeded 14 secrets in ${PROJECT_ID} (postgres-password is generated by Terraform itself)"
