[database]
host     =  localhost
port     =  5435
database =  bap
user     =  postgres    
password =  postgres
sslmode  =  disable

[tern]
migrations-dir      = migrations
version-table-schema = public
version-table        = schema_migrations
