[database]
host     = {{env "PGHOST" | default "localhost"}}
port     = {{env "PGPORT" | default "5435"}}
database = {{env "PGDATABASE" | default "bap"}}
user     = {{env "PGUSER" | default "postgres"}}
password = {{env "PGPASSWORD" | default "postgres"}}
sslmode  =  disable

[tern]
migrations-dir      = migrations
version-table-schema = public
version-table        = schema_migrations
