FROM golang:1.25-alpine AS builder
RUN go install github.com/jackc/tern/v2@latest

FROM alpine:3.20
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/tern /tern
COPY db/migrations /migrations
WORKDIR /migrations
CMD ["/tern", "migrate"]
